package com.phodal.routa.core.model

import kotlinx.serialization.Serializable

/**
 * The role of a message sender in a conversation.
 */
@Serializable
enum class MessageRole {
    /** Message from the system (system prompt, instructions). */
    SYSTEM,

    /** Message from a user or parent agent. */
    USER,

    /** Message generated by the agent (LLM response). */
    ASSISTANT,

    /** Message representing a tool call or tool result. */
    TOOL;
}

/**
 * A single message in an agent's conversation history.
 *
 * Messages are immutable records that form a chronological log
 * of an agent's interactions.
 */
@Serializable
data class Message(
    /** Unique identifier for this message. */
    val id: String,

    /** The agent this message belongs to. */
    val agentId: String,

    /** Who sent this message. */
    val role: MessageRole,

    /** The text content of the message. */
    val content: String,

    /** ISO-8601 timestamp. */
    val timestamp: String,

    /** Optional: the tool name if this is a tool call/result. */
    val toolName: String? = null,

    /** Optional: tool call arguments (JSON string). */
    val toolArgs: String? = null,

    /** Optional: the turn number in the conversation. */
    val turn: Int? = null,
)
